### ISSUE TITLE
Custom basis set syntax

### ISSUE THREAD

**Issue by LaTruelle** [cyllab/ccinput#1]
It seems to me that the parsing of custom basis sets is not working (I may be using the wrong syntax...).

**To Reproduce**
`ccinput g16 opt PBE0 --d3 -bs "C=631gd;H=631gd;Si=631gd;U=sddall;" -f 1-Singlet.xyz -o 1-Singlet.com`

**Actual behavior**
`!!! Unknown basis set: 'C=631gd;H=631gd;Si=631gd;U=sddall;' !!!`

Great idea and project anyway!

**Comment by RaphaelRobidas** [comment]
The problem with your command is that `-bs` is used instead of `-cbs`. The former expects only the name of the basis set, while the latter is for custom selection of basis sets, as you have done.

However, the syntax of the specified basis sets does not match that of the Basis Set Exchange package. Since it's not trivial to know what syntax they use exactly and since I already have a synonym system, it would be very useful to recognize synonyms and print a more helpful error message. I will add this feature in the future, thanks for the feedback!

In your case, the `6-31G(d)` basis set is named `6-31G*` in the Basis Set Exchange library. I'm not sure what the equivalent is for `SDDall`; you can search on the [BSE website](https://www.basissetexchange.org/). The basis set names used there will be the ones to request for custom basis sets.
